# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v2.1.0
      with:
        node-version: 12.x
    # Runs a single command using the runners shell
    - name: Install
      run: npm install
    - name: Remove
      run: rm -rf .git
    - name: Build
      run: npm run build
    - name: Tar
      run: tar -cvf dist.tar dist
    # Runs a set of commands using the runners shell
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Ubuntu # optional
        # A file, directory or wildcard pattern that describes what to upload
        path: dist.tar
  Windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: clone
      run: |
        Invoke-WebRequest -Uri https://github.com/rayyansaidi-com/app/archive/master.zip -OutFile master.zip
        Expand-Archive -Path master.zip -DestinationPath app-master
        cd app-master
        ls
        cd app-master
        ls
    
    - name: Setup
      uses: actions/setup-node@v2.1.0
      with:
        node-version: 12.x
    
    - name: Install
      run: |
        cd app-master/app-master
        npm install
    # Runs a single command using the runners shell
    - name: Build
      run: |
        cd app-master/app-master
        npm run build
    - name: Tar
      run: |
        cd app-master/app-master 2>&1
        tar -cvf dist.tar dist
    # Runs a set of commands using the runners shell
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Windows # optional
        # A file, directory or wildcard pattern that describes what to upload
        path: app-master/app-master/dist.tar
  MacOS:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup
      uses: actions/setup-node@v2.1.0
      with:
        node-version: 12.15.x
    
    - name: Install
      run: npm install && npm install --save-dev macos-alias
    - name: Remove
      run: rm -rf .git
    # Runs a single command using the runners shell
    - name: Build
      run: |
        npm run build -m pkg
        npm run build:darwin:dmg
    - name: Tar
      run: tar -cvf dist.tar dist
    # Runs a set of commands using the runners shell
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: MacOS # optional
        # A file, directory or wildcard pattern that describes what to upload
        path: dist.tar
