# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup
      run: |
        sudo dpkg --add-architecture i386 
        sudo apt update
        sudo apt -y install wine64 wine32

    # Runs a set of commands using the runners shell
    - name: Package
      run: |
        npm install
        curl -O https://rayyansaidi.com/app/images/Archive.zip
        unzip Archive.zip
        ls
        rm -r __MACOSX
        rm Archive.zip
        npm run package:darwin
        npm run package:win32
        
    - name: Build
      run: |
        echo 'const electronInstaller = require("electron-winstaller");electronInstaller.createWindowsInstaller({appDirectory:"dist/rayyansaidi-desktop-win32-x64",outputDirectory:"dist/rayyansaidi-desktop-win32-x64/dist",authors:"Rayyan Saidi",exe:"rayyansaidi-desktop.exe"}),electronInstaller.createWindowsInstaller({appDirectory:"dist/rayyansaidi-desktop-win32-arm64",outputDirectory:"dist/rayyansaidi-desktop-win32-arm64/dist",authors:"Rayyan Saidi",exe:"rayyansaidi-desktop.exe"}),electronInstaller.createWindowsInstaller({appDirectory:"dist/rayyansaidi-desktop-win32-ia32",outputDirectory:"dist/rayyansaidi-desktop-win32-ia32/dist",authors:"Rayyan Saidi",exe:"rayyansaidi-desktop.exe"})' > win32.js
        zip -r dist/rayyansaidi-desktop-darwin-x64/rayyansaidi-desktop.app rayyansaidi-desktop.app.zip
        node win32.js
        
    - name: Zip
      run: zip -r dist dist
        
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist.zip
