# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Test
      run: |
       npm install
       npm start &
       sleep 5
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Test
      run: |
       npm install
       npm start &
       sleep 5
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Test
      run: |
       npm install
       npm start &
       sleep 5
